services:
  # Full-stack service (Frontend + Backend)
  - type: web
    name: calendar-app
    runtime: node
    env: node
    buildCommand: npm run build:full
    startCommand: npm run server:start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://denisshevchenko109:AmeEP9TVkyqzt6TJ@calendar.mrelvfx.mongodb.net/?retryWrites=true&w=majority&appName=Calendar
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: JWT_COOKIE_EXPIRE
        value: 30
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: VITE_API_URL
        value: /api
      - key: VITE_NODE_ENV
        value: production
      - key: VITE_SYNC_ENABLED
        value: true
